sylius_grid:
    grids:
        setono_sylius_gift_card_admin_gift_card_code_order:
            extends: sylius_admin_order
            driver:
                options:
                    repository:
                        method: createQueryBuilderByGiftCardCodeId
                        arguments:
                            giftCardCodeId: $id
