setono_sylius_gift_card_admin_product_create_gift_card:
    path: /products/new/gift-card
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.product:createAction
        _sylius:
            section: admin
            permission: true
            factory:
                method: createWithVariant
            template: SyliusAdminBundle:Crud:create.html.twig
            redirect: sylius_admin_product_update
            form:
                options:
                    is_gift_card: true
            vars:
                subheader: sylius.ui.manage_your_product_catalog
                templates:
                    form: SyliusAdminBundle:Product:_form.html.twig
                route:
                    name: setono_sylius_gift_card_admin_product_create_gift_card

setono_sylius_gift_card_admin_gift_card_code:
    resource: |
        alias: setono_sylius_gift_card.gift_card_code
        section: admin
        only: [index, delete, bulkDelete]
        templates: SyliusAdminBundle:Crud
        redirect: index
        grid: setono_sylius_gift_card_admin_gift_card_code
        vars:
            all:
                subheader: setono_sylius_gift_card.ui.gift_card_code
                templates:
                    form: "@SetonoSyliusGiftCardPlugin/Admin/GiftCardCode/_form.html.twig"
            index:
                icon: 'gift'
    type: sylius.resource

setono_sylius_gift_card_admin_gift_card_code_create_for_channel:
    path: /gift-card-codes/create
    methods: [GET]
    defaults:
        _controller: sylius.controller.channel:indexAction
        _sylius:
            repository:
                method: findAll
            template: "@SetonoSyliusGiftCardPlugin/Admin/GiftCardCode/create.html.twig"
            permission: true

setono_sylius_gift_card_admin_gift_card_code_create:
    path: /gift-card-codes/create/{channelCode}
    methods: [GET, POST]
    defaults:
        _controller: setono_sylius_gift_card.controller.gift_card_code:createAction
        _sylius:
            factory:
                method: createForChannel
                arguments:
                    channel: "expr:service('sylius.repository.channel').findOneByCode($channelCode)"
            template: SyliusAdminBundle:Crud:create.html.twig
            grid: setono_sylius_gift_card_admin_gift_card_code
            section: admin
            redirect:
                route: setono_sylius_gift_card_admin_gift_card_code_index
            permission: true
            vars:
                route:
                    parameters:
                        channelCode: $channelCode
                templates:
                    form: "@SetonoSyliusGiftCardPlugin/Admin/GiftCardCode/_form.html.twig"
