setono_sylius_gift_card_shop_search_gift_card:
    path: /gift-card/search
    methods: [GET,POST]
    defaults:
        _controller: setono_sylius_gift_card.controller.action.search_gift_card

setono_sylius_gift_card_shop_remove_gift_card_from_order:
    path: /gift-card/{giftCard}/remove-from-order
    methods: GET
    defaults:
        _controller: setono_sylius_gift_card.controller.action.remove_gift_card_from_order

setono_sylius_gift_card_shop_partial_add_gift_card_to_order:
    path: /_partial/gift-card/add-to-order
    methods: GET
    defaults:
        _controller: setono_sylius_gift_card.controller.action.add_gift_card_to_order
