setono_sylius_gift_card_shop_ajax_add_gift_card_to_order:
    path: /gift-card/add-to-order
    methods: POST
    defaults:
        _controller: setono_sylius_gift_card.controller.action.add_gift_card_to_order
        _format: json
