sylius_resource:
    resources:
        setono_sylius_gift_card_plugin.gift_card:
            driver: doctrine/orm
            classes:
                model: Setono\SyliusGiftCardPlugin\Entity\GiftCard
                interface: Setono\SyliusGiftCardPlugin\Entity\GiftCardInterface
                factory: Setono\SyliusGiftCardPlugin\Factory\GiftCardFactory

        setono_sylius_gift_card_plugin.gift_card_code:
            driver: doctrine/orm
            classes:
                model: Setono\SyliusGiftCardPlugin\Entity\GiftCardCode
                interface: Setono\SyliusGiftCardPlugin\Entity\GiftCardCodeInterface
