imports:
    - { resource: "@SetonoSyliusGiftCardPlugin/Resources/config/state_machine/sylius_order_payment.yml" }
    - { resource: "@SetonoSyliusGiftCardPlugin/Resources/config/state_machine/sylius_order.yml" }
