winzou_state_machine:
    sylius_order:
        callbacks:
            after:
                setono_increment_gift_cards_usages:
                    on: ["create"]
                    do: ["@setono_sylius_gift_card.modifier.order_gift_card_usage", "increment"]
                    args: ["object"]
                setono_decrement_gift_cards_usages:
                    on: ["cancel"]
                    do: ["@setono_sylius_gift_card.modifier.order_gift_card_usage", "decrement"]
                    args: ["object"]
                setono_cancellation_gift_card_codes:
                    on: ["cancel"]
                    do: ["@setono_sylius_gift_card.operator.order_gift_card", "disable"]
                    args: ["object"]
