winzou_state_machine:
    sylius_order_checkout:
        callbacks:
            after:
                setono_gift_card_create:
                    on: ["complete"]
                    do: ["@setono_sylius_gift_card.operator.order_gift_card", "associateToCustomer"]
                    args: ["object"]
