imports:
    - { resource: "@SetonoSyliusGiftCardPlugin/Resources/config/grids.yaml" }
    - { resource: "@SetonoSyliusGiftCardPlugin/Resources/config/sylius_ui.yaml" }

    - { resource: "@SetonoSyliusGiftCardPlugin/Resources/config/state_machine/sylius_order.yaml" }
    - { resource: "@SetonoSyliusGiftCardPlugin/Resources/config/state_machine/sylius_order_checkout.yaml" }
    - { resource: "@SetonoSyliusGiftCardPlugin/Resources/config/state_machine/sylius_order_payment.yaml" }

sylius_mailer:
    emails:
        gift_card_customer:
            subject: setono_sylius_gift_card.email.new_gift_card
            template: "@SetonoSyliusGiftCardPlugin/Email/giftCardToCustomer.html.twig"
        gift_card_order:
            subject: setono_sylius_gift_card.email.your_gift_cards_you_bought_in_the_order
            template: "@SetonoSyliusGiftCardPlugin/Email/giftCardsFromOrder.html.twig"

jms_serializer:
    metadata:
        directories:
            setono-sylius-gift-card-sylius:
                namespace_prefix: "Setono\\SyliusGiftCardPlugin\\Model"
                path: "@SetonoSyliusGiftCardPlugin/Resources/config/serializer"

liip_imagine:
    filter_sets:
        setono_sylius_gift_card_background:
            filters:
                thumbnail: { size: [1200], mode: inset }

sylius_ui:
    events:
        setono_sylius_gift_card.admin.gift_card_configuration.update.javascripts:
            blocks:
                live_pdf_rendering_js: '@SetonoSyliusGiftCardPlugin/Admin/GiftCardConfiguration/Update/_javascripts.html.twig'
        
        setono_sylius_gift_card.admin.gift_card.create.javascripts:
            blocks:
                send_customer_email_js: '@SetonoSyliusGiftCardPlugin/Admin/GiftCard/Create/_javascripts.html.twig'
        
        setono_sylius_gift_card.shop.account.gift_card.index.after_content_header:
            blocks:
                after_content_header_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 50
                    context:
                        event: setono_sylius_gift_card.shop.account.gift_card.index.after_content_header
        
        setono_sylius_gift_card.shop.account.gift_card.index.after_grid:
            blocks:
                after_content_header_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 50
                    context:
                        event: setono_sylius_gift_card.shop.account.gift_card.index.after_grid
        
        setono_sylius_gift_card.shop.account.gift_card.index.header:
            blocks:
                after_content_header_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 50
                    context:
                        event: setono_sylius_gift_card.shop.account.gift_card.index.header
        
        setono_sylius_gift_card.shop.cart.summary.applied_gift_cards:
            blocks:
                after_content_header_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 50
                    context:
                        event: setono_sylius_gift_card.shop.cart.summary.applied_gift_cards
