sylius_fixtures:
    suites:
        default:
            fixtures:
                currency:
                    options:
                        currencies: 
                            - "EUR"
                geographical:
                    options:
                        countries:
                            - "US"
                            - "DK"
                channel:
                    options:
                        custom:
                            eu_web_store:
                                name: "EU Web Store"
                                code: "EU_WEB"
                                locales:
                                    - "%locale%"
                                currencies:
                                    - "EUR"
                                enabled: true
                                hostname: "localhost"
                payment_method:
                    options:
                        custom:
                            bank:
                                code: "bank"
                                name: "Bank"
                                channels:
                                    - "EU_WEB"
                                enabled: true
                shipping_method:
                    options:
                        custom:
                            ukrposhta:
                                code: "ukrposhta"
                                name: "UkrPoshta"
                                channels:
                                    - "EU_WEB"
                                enabled: true
                taxon:
                    options:
                        custom:
                            category:
                                code: category
                                name: Category
                                children:
                                  - code: gift_cards
                                    name: Buy Gift Card
                product_option:
                    options:
                        custom:
                            product_option_gift_card_basic_amount:
                                name: Gift card amount
                                code: gift_card_basic_amount
                                values:
                                    gift_card_amount_100: "100.00"
                                    gift_card_amount_200: "200.00"
                                    gift_card_amount_500: "500.00"
                                    gift_card_amount_1000: "1000.00"
                product:
                    options:
                        custom:
                            product_setono_sticker:
                                name: "Setono Sticker"
                                code: "setono_sticker"
                                channels:
                                    - "US_WEB"
                                    - "EU_WEB"
                            product_gift_card_basic:
                                name: "Basic Gift Card"
                                code: "gift_card_basic"
                                main_taxon: "gift_cards"
                                taxons: 
                                    - "gift_cards"
                                channels:
                                    - "US_WEB"
                                    - "EU_WEB"
                                product_options: 
                                    - "gift_card_basic_amount"
                            product_platinum_gift_card:
                                name: "Platinum Gift Card"
                                code: "gift_card_platinum"
                                main_taxon: "gift_cards"
                                taxons: 
                                    - "gift_cards"
                                channels:
                                    - "US_WEB"
                setono_sylius_gift_card:
                    options:
                        custom:
                            gift_card_basic:
                                product: "gift_card_basic"
                                channels: 
                                    - "US_WEB"
                                # Amounts will be taken from related product option
                                amount_product_option: "gift_card_basic_amount"
                                codes_count: 10 # How much gift card codes should be created?
                                # codes_used_count: 6
                            gift_card_platinum:
                                product: "gift_card_platinum"
                                channels: 
                                    - "US_WEB"
                                    - "EU_WEB"
                                # Amount will be taken from `amount` option as related product is simple
                                amount: 10000.00
                                codes_count: 4
                setono_sylius_gift_card_payed_order:
                    options:
                        custom:
                            gift_card_payed_orders:
                                customer: "shop@example.com"
                                channel: "US_WEB"
                                locale: "%locale%"
                                currency: "EUR"
                                # gift_card_codes_count: 2
                                address:
                                    first_name: "Igor"
                                    country: "DK"
                                shipping_method: "ukrposhta"
                                payment_method: "bank"
                                items:
                                    - product: "setono_sticker"
                                      quantity: 3
                                checkout_completed_at: "-1 days"
