Sylius\Component\Customer\Model\Customer:
    exclusion_policy: ALL
    xml_root_name: sylius_customer
    properties:
        email:
            expose: true
            type: string
            groups: [Autocomplete]
